const express = require("express");
const router = express.Router();
const wrapAsync = require("../utils/wrapAsync");
const { isLoggedIn, isAdmin } = require("../middleware");
const admin = require("../controllers/admin");
router.get("/", isLoggedIn, isAdmin, wrapAsync(admin.dashboard));
router.get("/users", isLoggedIn, isAdmin, wrapAsync(admin.renderUsers));
router.post("/users/:id/block", isLoggedIn, isAdmin, wrapAsync(admin.toggleBlockUser));
router.delete("/users/:id", isLoggedIn, isAdmin, wrapAsync(admin.deleteUser));
router.get("/services", isLoggedIn, isAdmin, wrapAsync(admin.renderServices));
router.post("/services/:type/:id/availability", isLoggedIn, isAdmin, wrapAsync(admin.setServiceAvailability));
router.delete("/services/:type/:id", isLoggedIn, isAdmin, wrapAsync(admin.deleteService));
router.post("/payments/:id/settle", isLoggedIn, isAdmin, wrapAsync(admin.settlePayment));
router.post("/payout-requests/:id", isLoggedIn, isAdmin, wrapAsync(admin.processPayoutRequest));
module.exports = router;
